apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core-services

resources:
- deployment.yaml
- hpa.yaml
- networkpolicy.yaml
- service.yaml
- serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: urlshortener
  app.kubernetes.io/instance: urlshortener
